# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bac3516727fbd9023c1b93cb494c0ab7a9b51254d21d114a67f971da76429033bf189c4f95ce3870d26f12b950dd1b552c02d32033d308cf680de7f10774567b

test:
  secret_key_base: 11224b070bc0f150ba8aabf69590abe872a89e5a60a6b617049ffa588aa0677f2ab254303a741039d38e0526fdd8d3a812819efc01460d3576139b7303cdbec3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
